name: mighty_news
description: App demo news LE.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.7+2
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  html: ^0.15.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.2
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  share: ^2.0.4
  onesignal_flutter: ^3.2.0
  package_info: ^2.0.2

  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  firebase_remote_config: ^0.10.0+4
  firebase_crashlytics: ^2.2.0
  google_mobile_ads: ^0.13.3
  google_sign_in: ^5.0.7

  flutter_html: ^2.1.1
  video_player: ^2.1.14

  cached_network_image: ^3.1.0
  geolocator: ^7.4.0
  flutter_tts: ^3.2.2
  clippy_flutter: ^2.0.0-nullsafety.1
  image_picker: ^0.8.3+2
  flutter_vector_icons: ^1.0.0
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  photo_view: ^0.12.0

  shimmer: ^2.0.0
  fading_edge_scrollview: ^2.0.0

  story_view: ^0.13.1

  rive: ^0.7.28

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  mobx_codegen: ^2.0.1+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons: "^0.9.2"
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/
    - assets/rive/
